#+AUTHOR:Philip Tham
#+TITLE:A Lazy to Strict Language Compiler (Tentative)
#+OPTIONS: toc:nil

\newpage

* Introduction

The main difference between lazy and strict programming languages is the steps
of evaluation that their respective compilers take. While a strict language
always fully evaluates all the expressions given as parameters, a lazy language
only evaluates expressions when needed. This means that lazy languages can make
use of infinite data structures and potentially non-terminating function calls.

This project aims to create a compiler that takes code from a lazy programming
language and compiles it in to a strict programming language in order to 
formalize the connection between the two. This compiler will be written in
the programming language Haskell. 
*The source and destination languages will be left open for discussion for now.*

\noindent
Possible lazy source languages:
+ CakeML
+ Haskell

\noindent
Possible strict destination languages:
+ C#
+ Python

It is necessary to show that the compiler correctly expresses laziness in the
strict language. Operational semantics will be used to prove that the steps of
evaluation are correct. If time allows for it, the compiler will also be tested
for correctness by using the Haskell library QuickCheck.


* Limitations of the Project

+ GHC version?
+ Might not support all types of operations depending on time


* Related Courses
** Programming Language Technology (PLT) and Compiler Construction
The courses PLT and Compiler Construction are basically the cornerstones of this
project, as it is about creating a compiler that connects two different types of
programming languages.

** Models of Computation
Models of Computation discusses different computation models. This includes
programming language of both lazy and strict evaluation processes. For example,
there is the minimalistic (and theoretical) programming language /X/ (Chi) that
models lambda calculus. The language includes /weak head normal form/ (lazy 
evaluation of certain expressions) and full (strict) evaluation.

** Introduction to Functional Programming and Advanced Functional Programming (?)
As this project will be utilizing functional languages (and most likely
programmed in Haskell), these are necessary courses. It is quite possible that
the compilers one has created in PLT and Compiler Construction were written in
Haskell. In such case, these courses may be implied to have been already
completed.


* Literature List
Books:
+ http://dragonbook.stanford.edu/
+ https://www.elsevier.com/books/engineering-a-compiler/cooper/978-0-12-088478-0
+ http://research.microsoft.com/en-us/um/people/simonpj/Papers/pj-lester-book/
+ http://www1.digitalgrammars.com/ipl-book/
